spring:
  shardingsphere:
    datasource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://182.92.69.8:3306/wuw?useUnicode=true&characterEncoding=utf&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: Root_12root
        driver-class-name: com.mysql.cj.jdbc.Driver  # 使用的mysql8
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://8.142.23.42:3306/wuw?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
        username: root
        password: Root_12root
        driver-class-name: com.mysql.cj.jdbc.Driver  # 使用的mysql8
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            write-data-source-name: ds0
            read-data-source-names: ds1
            load-balancer-name: load
        load-balancers:
          load:
            type: ROUND_ROBIN
  # redis配置
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 182.92.69.8 # Redis 服务器地址
    port: 26381 # Redis 服务器连接端口
    password: 123456 # Redis 服务器连接密码（默认为空）
    timeout:  5000  # 连接超时，单位ms
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  redisson:
    config-file:
      yaml: classpath:redisson.yml
  elasticsearch:
    rest:
      # 定位ES的位置
      uris: http://8.142.23.42:9200
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: 182.92.69.8:9876
  #生产者配置
  producer:
    #组名
    group: anran-producer-group
    #目的地（topic:tag）
    #topic
    topic: test
    #sync tag(同步消息tag)
    sync-tag: anran-sync-tags
    #async tag(异步消息tag)
    async-tag: anran-async-tags
    #oneway tag(单向消息tag)
    oneway-tag: anran-oneway-tags
    #消费者配置
  consumer:
    #组名
    group: anran-consumer-group
    #监听主题
    topic: test
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）
    tags: anran-sync-tags||anran-async-tags||anran-oneway-tags
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://8.142.23.42:9080/xxl-job-admin
    executor:
      address: ''
      appname: ucenter
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999


#mysql
mysql-ds:
  #主库
  master:
    jdbc-url: jdbc:mysql://182.92.69.8:3306/wuw?characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root_12root
  #读库1
  replica-1:
    jdbc-url: jdbc:mysql://8.142.23.42:3306/wuw?characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Root_12root
elasticsearch:
  host: 8.142.23.42
  port: 9200

