
spring:
  datasource:
    url: jdbc:mysql://182.92.69.8:3306/wuw?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Root_12root
    driver-class-name: com.mysql.cj.jdbc.Driver  # 使用的mysql8
    type: com.alibaba.druid.pool.DruidDataSource
    #配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #后台监控
    filters: stat,wall,slf4j

    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # redis配置
  redis:
    database: 0 # Redis 数据库索引（默认为 0）
    host: 182.92.69.8 # Redis 服务器地址
    port: 26381 # Redis 服务器连接端口
    password: 123456 # Redis 服务器连接密码（默认为空）
    timeout:  5000  # 连接超时，单位ms
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  redisson:
    config-file:
      yaml: classpath:redisson.yml




